name: Generate GIFs

on:
  workflow_dispatch:
    inputs:
      resolution:
        description: Resolution in "1:2" style
        required: true
        type: string

jobs:
  transcode:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Download from S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.s3_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.s3_secret_key }}
          AWS_DEFAULT_REGION: ru-central1
          AWS_EC2_METADATA_DISABLED: true
        run: |
          aws s3 sync ${{ secrets.bucket_name }} . --endpoint-url=https://storage.yandexcloud.net
      - name: Setup ffmpeg 
        uses: FedericoCarboni/setup-ffmpeg@v2
        id: setup-ffmpeg
      - name: Run ffmpeg script with resolution ${{ inputs.resolution }}
        run: |
         chmod +x script.sh
         ./script.sh ${{ inputs.resolution }}
        shell: bash
      - name: Pack gifs
        run: |
          mkdir gifs
          mv *.gif gifs
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: gifs
